version: "3.7"
services:
  nginx:
    image: ramosisw/nginx-proxy-manager:latest
    container_name: nginx
    hostname: nginx
    build:
      context: .
    restart: always
    networks: 
      # dns:
      nginx:
        ipv4_address: 192.168.80.2
    ports:
      - 80:80
      # - 81:81
      - 443:443
    volumes:
      - ./data/config.json:/app/config/production.json
      - ./data/data:/data
      - ./data/db:/db
      - ./data/letsencrypt:/etc/letsencrypt
    environment:
      - FORCE_COLOR=1
networks:
  # dns:
  #   external: true
  nginx:
    name: nginx
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.80.0/28
